server:
  port: 8094

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;Databasename=sys
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123456


  jpa:
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
  resources:
    static-locations: classpath:c,classpath:static
  mvc:
    view:
      prefix:
      suffix: .html
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8


#mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: com.example.entity




logging:
  level:
    com:
      example:
        mapper : debug
mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity
  configuration:
    map-underscore-to-camel-case: true